import test from 'node:test'; import assert from 'node:assert/strict'; import fixture from './fixtures/delegation-event-graph/recorded-handoff.json'; import { delegationGraph, recordedDelegationGraphEdges } from '../src/core/delegationGraph'; import type { Task } from '../src/core/model';
const task = (id: string): Task => ({ id, title: id, prompt: '', repository: 'C:/repo', worktree: `C:/w/${id}`, branch: `agent/x-${id}`, baseCommit: 'a'.repeat(40), integrationTarget: 'main', provider: 'codex', interface: 'managed-cli', state: 'idle', createdAt: '2026-09-18T00:00:00.000Z', updatedAt: '2026-09-18T00:00:00.000Z' });
test('delegation graph uses only persisted assignment and dependency records', () => { const parent = task('111111111111'), prior = task('222222222222'), child = task('333333333333'); child.delegation = { parentId: parent.id, runId: 'aaaaaaaaaaaa', childKey: 'child', dispatchKey: 'b'.repeat(24), dependencies: [prior.id] }; child.schedule = { state: 'enrolled', dependencies: [prior.id], artifacts: [] }; assert.deepEqual(delegationGraph([parent, prior, child]), [{ from: parent.id, to: child.id, kind: 'assignment', state: 'queued' }, { from: prior.id, to: child.id, kind: 'dependency', state: 'queued' }]); });
test('foreign or missing durable links never become graph arrows', () => { const child = task('333333333333'); child.delegation = { parentId: '111111111111', runId: 'aaaaaaaaaaaa', childKey: 'child', dispatchKey: 'b'.repeat(24), dependencies: [] }; child.repository = 'C:/other'; assert.deepEqual(delegationGraph([child]), []); });
test('only supplied matching event fixtures create handoff motion; approvals pause and terminal routes stop', () => { const parent = task('111111111111'), child = task('333333333333'); child.delegation = { parentId: parent.id, runId: 'aaaaaaaaaaaa', childKey: 'child', dispatchKey: 'b'.repeat(24), dependencies: [] }; const paused = recordedDelegationGraphEdges([parent, child], fixture); assert.deepEqual(paused.approvalTargets, [child.id]); assert.equal(paused.edges[0]!.state, 'paused'); assert.equal(paused.edges[0]!.provenance.producer, 'host'); const moving = recordedDelegationGraphEdges([parent, child], fixture.slice(0, 1)); assert.equal(moving.edges[0]!.state, 'moving'); child.reviewedCommit = { commit: 'b'.repeat(40), tree: 'c'.repeat(40), baseCommit: 'a'.repeat(40), reviewedAt: '2026-09-18T00:00:02.000Z' }; assert.equal(recordedDelegationGraphEdges([parent, child], fixture.slice(0, 1)).edges[0]!.state, 'stopped'); const result = { ...fixture[0]!, id: 'e'.repeat(24), sequence: 2, kind: 'result-delivery', from: { kind: 'task', taskId: child.id }, to: { kind: 'task', taskId: parent.id }, provenance: { producer: 'host', recordId: 'f'.repeat(24) } }; assert.equal(recordedDelegationGraphEdges([parent, child], [result]).edges[0]!.state, 'stopped'); assert.deepEqual(recordedDelegationGraphEdges([parent, child], []).edges, []); });
test('recorded events cannot fabricate a route without the exact child parent/run receipt', () => { const parent = task('111111111111'), child = task('333333333333'); assert.deepEqual(recordedDelegationGraphEdges([parent, child], fixture.slice(0, 1)).edges, []); child.delegation = { parentId: parent.id, runId: 'bbbbbbbbbbbb', childKey: 'child', dispatchKey: 'b'.repeat(24), dependencies: [] }; assert.deepEqual(recordedDelegationGraphEdges([parent, child], fixture.slice(0, 1)).edges, []); });
test('foreign parent or run approval pauses cannot pause a matching visual route', () => { const parent = task('111111111111'), child = task('333333333333'); child.delegation = { parentId: parent.id, runId: 'aaaaaaaaaaaa', childKey: 'child', dispatchKey: 'b'.repeat(24), dependencies: [] }; assert.equal(recordedDelegationGraphEdges([parent, child], fixture.slice(0, 1)).edges[0]!.state, 'moving'); const foreignParent = { ...fixture[1]!, id: 'e'.repeat(24), parentId: '222222222222' }; const foreignRun = { ...fixture[1]!, id: 'f'.repeat(24), runId: 'bbbbbbbbbbbb' }; for (const pause of [foreignParent, foreignRun]) assert.deepEqual(recordedDelegationGraphEdges([parent, child], [pause]).approvalTargets, []); });
test('a durable scheduler dispatch projects an actual arrow without fabricating a task source', () => {
  const parent = task('111111111111'), child = task('333333333333');
  child.delegation = { parentId: parent.id, runId: 'aaaaaaaaaaaa', childKey: 'child', dispatchKey: 'b'.repeat(24), dependencies: [] };
  const dispatch = { ...fixture[0]!, id: 'd'.repeat(24), sequence: 3, kind: 'dispatch' as const, from: { kind: 'scheduler' as const }, to: { kind: 'task' as const, taskId: child.id }, provenance: { producer: 'scheduler' as const, recordId: 'e'.repeat(24) } };
  assert.deepEqual(recordedDelegationGraphEdges([parent, child], [dispatch]).edges, [{ id: dispatch.id, to: child.id, kind: 'dispatch', provenance: dispatch.provenance, state: 'moving' }]);
});
