import test from 'node:test'; import assert from 'node:assert/strict';
import { assertFreshContextRequest, prepareContextRequest } from '../src/core/delegationContextRequests';
const binding = { parentId: '111111111111', runId: '222222222222', childKey: 'parser', writeScope: ['src/parser', 'tests/parser.test.ts'] };
const request = () => ({ version: 1, parentId: binding.parentId, runId: binding.runId, childKey: binding.childKey, requestKey: 'a'.repeat(24), requested: [{ id: 'parser-api', path: 'src/parser/api.ts', revision: 'b'.repeat(40), sha256: 'c'.repeat(64), reason: 'Need the current parser return contract.' }] });
test('context requests are bounded, scoped, provenance-bearing, and fresh only at their recorded revision', () => { const receipt = prepareContextRequest(request(), binding); assert.equal(receipt.sha256.length, 64); assert.deepEqual(JSON.parse(JSON.stringify(receipt)), receipt); assert.doesNotThrow(() => assertFreshContextRequest(receipt, binding, { 'parser-api': { revision: 'b'.repeat(40), sha256: 'c'.repeat(64) } })); assert.throws(() => assertFreshContextRequest(receipt, binding, { 'parser-api': { revision: 'd'.repeat(40), sha256: 'c'.repeat(64) } }), /changed/); });
test('context requests reject scope expansion, duplicates, malformed provenance, and cross-run identity', () => { const outside = request(); outside.requested[0]!.path = 'src/other.ts'; assert.throws(() => prepareContextRequest(outside, binding), /outside/); const duplicate = request(); duplicate.requested.push({ ...duplicate.requested[0]!, id: 'other' }); assert.throws(() => prepareContextRequest(duplicate, binding), /Duplicate/); const malformed = request(); malformed.requested[0]!.sha256 = 'no'; assert.throws(() => prepareContextRequest(malformed, binding), /SHA/); const foreign = request(); foreign.runId = '333333333333'; assert.throws(() => prepareContextRequest(foreign, binding), /different/); });
test('unrelated history cannot enter a context request', () => { const extra = { ...request(), transcript: 'all parent messages' }; assert.throws(() => prepareContextRequest(extra, binding), /Invalid delegation fields/); });
test('a host can authorize focused read context without treating write scope as a sandbox', () => { const readable = { ...request(), requested: [{ ...request().requested[0]!, path: 'src/contracts/parser.ts' }] }; assert.throws(() => prepareContextRequest(readable, binding), /outside/); assert.doesNotThrow(() => prepareContextRequest(readable, { ...binding, readScope: ['src/parser', 'src/contracts'] })); });
test('freshness re-parses malformed receipts even when their attacker recomputes the hash', () => { const receipt = prepareContextRequest(request(), binding); const malformed: any = { ...receipt, requested: [{ ...receipt.requested[0]!, path: 'src/other.ts' }] }; malformed.sha256 = prepareContextRequest({ ...request(), requested: malformed.requested }, { ...binding, readScope: ['src/other.ts'] }).sha256; assert.throws(() => assertFreshContextRequest(malformed, binding, {}), /outside/); });
