import test from 'node:test'; import assert from 'node:assert/strict';
import { projectDelegationReconciliation } from '../src/core/delegationReconciliation'; import type { Task } from '../src/core/model';
const now = '2026-09-19T00:00:00.000Z', base = 'a'.repeat(40), parentId = '111111111111', runId = '222222222222';
const parent = (): Task => ({ id: parentId, title: 'Parent', prompt: 'x', repository: 'C:/repo', worktree: 'C:/parent', branch: 'agent/parent', baseCommit: base, integrationTarget: 'main', provider: 'codex', interface: 'managed-cli', state: 'idle', createdAt: now, updatedAt: now });
const child = (id: string, key: string): Task => ({ id, title: key, prompt: 'x', repository: 'C:/repo', worktree: `C:/${key}`, branch: `agent/${key}-123456789abc`, baseCommit: base, integrationTarget: 'main', provider: 'codex', interface: 'managed-cli', state: 'idle', createdAt: now, updatedAt: now, delegation: { parentId, runId, childKey: key, dispatchKey: key === 'one' ? 'a'.repeat(24) : 'b'.repeat(24), dependencies: [] } });
test('reconciliation projects pending dispatch, uncertainty, cancellation, journal recovery, budget holds and restart without mutation', () => {
  const p = parent(), one = child('333333333333', 'one'), two = child('444444444444', 'two'); one.schedule = { state: 'blocked', dependencies: [], artifacts: [], uncertain: true, budgetHold: true }; one.delegationJournalPending = { version: 1, event: { version: 1, id: 'a'.repeat(24), occurredAt: now, kind: 'assignment', parentId, runId, from: { kind: 'task', taskId: parentId }, to: { kind: 'task', taskId: one.id }, provenance: { producer: 'host', recordId: 'a'.repeat(24) } } }; two.schedule = { state: 'cancelled', dependencies: [], artifacts: [] }; two.state = 'interrupted';
  const view = projectDelegationReconciliation(p, runId, [p, one, two], [{ version: 1, parentId, runId, childKey: 'one', dispatchKey: 'a'.repeat(24), worktreeId: 'c'.repeat(12), baseCommit: base, status: 'reserved', createdAt: now, updatedAt: now }], { events: [], contextRequests: [], results: [] });
  assert.equal(view.children[0]!.pendingDispatch, true); assert.equal(view.children[0]!.uncertainWriter, true); assert.equal(view.children[0]!.journalRecovery, true); assert.equal(view.children[0]!.budgetHold, true); assert.equal(view.children[1]!.cancelled, true); assert.equal(view.children[1]!.restart, 'interrupted'); assert.equal(one.schedule?.state, 'blocked');
});
test('missing durable sources remain unavailable and projection has no process hooks', () => { const p = parent(), c = child('333333333333', 'one'); const view = projectDelegationReconciliation(p, runId, [p, c]); assert.equal(view.availability, 'unavailable'); assert.equal(view.journal, 'unavailable'); assert.equal(view.children[0]!.pendingDispatch, true); });
test('a mismatched dispatch cannot clear pending state after restart', () => { const p = parent(), c = child('333333333333', 'one'); const view = projectDelegationReconciliation(p, runId, [p, c], [{ version: 1, parentId, runId, childKey: 'one', dispatchKey: 'f'.repeat(24), worktreeId: 'c'.repeat(12), baseCommit: base, status: 'materialized', worktree: 'C:/one', branch: 'agent/one-123456789abc', createdAt: now, updatedAt: now }]); assert.equal(view.children[0]!.pendingDispatch, true); assert.equal(c.schedule, undefined); });
