import test from 'node:test'; import assert from 'node:assert/strict';
import { assertDelegationResultIntegrity, prepareDelegationResult } from '../src/core/delegationResults';
const binding = { parentId: '111111111111', runId: '222222222222', childKey: 'parser', dispatchKey: 'a'.repeat(24), baseCommit: 'b'.repeat(40), writeScope: ['src/parser', 'tests/parser.test.ts'], dependencies: [{ childKey: 'schema', receiptSha256: 'c'.repeat(64) }] };
const result = () => ({ version: 1, parentId: binding.parentId, runId: binding.runId, childKey: binding.childKey, dispatchKey: binding.dispatchKey, baseCommit: binding.baseCommit, commit: 'd'.repeat(40), tree: 'e'.repeat(40), changedPaths: ['src/parser/index.ts'], decisions: 'Kept the existing return shape.', summary: 'Parser completed.', unresolved: [], validations: [{ command: 'npm.cmd test -- parser', status: 'passed', evidenceRefs: ['check-log'] }], evidence: [{ id: 'check-log', kind: 'log', label: 'Focused test output', path: 'artifacts/parser-test.log', sha256: 'f'.repeat(64) }], dependencies: binding.dependencies });
test('result receipts bind exact commit/tree/evidence/dependencies and survive JSON round trip', () => { const receipt = prepareDelegationResult(result(), binding); assert.equal(receipt.commit, 'd'.repeat(40)); assert.deepEqual(JSON.parse(JSON.stringify(receipt)), receipt); assert.doesNotThrow(() => assertDelegationResultIntegrity(receipt, binding)); });
test('results reject cross-run scope, dependency, malformed evidence, and changed integrity', () => { const foreign = result(); foreign.runId = '333333333333'; assert.throws(() => prepareDelegationResult(foreign, binding), /different/); const outside = result(); outside.changedPaths = ['src/other.ts']; assert.throws(() => prepareDelegationResult(outside, binding), /outside/); const dependency = result(); dependency.dependencies = []; assert.throws(() => prepareDelegationResult(dependency, binding), /dependencies/); const malformed = result(); malformed.evidence[0]!.sha256 = 'x'; assert.throws(() => prepareDelegationResult(malformed, binding), /SHA/); const receipt = prepareDelegationResult(result(), binding); receipt.summary = 'changed'; assert.throws(() => assertDelegationResultIntegrity(receipt, binding), /changed/); });
test('result receipts reject copied logs or unrelated history fields', () => { const copied = { ...result(), transcript: 'all parent and sibling history' }; assert.throws(() => prepareDelegationResult(copied, binding), /Invalid delegation fields/); });
test('result summaries refuse transcript and terminal-log shaped free text', () => { const log = result(); log.summary = 'TAP version 13\n# Subtest: copied full output'; assert.throws(() => prepareDelegationResult(log, binding), /concise summary/); const transcript = result(); transcript.decisions = '[assistant]: copied parent transcript'; assert.throws(() => prepareDelegationResult(transcript, binding), /concise summary/); });
test('integrity re-parses scope and dependencies even when an attacker recomputes a receipt hash', () => { const receipt: any = prepareDelegationResult(result(), binding); receipt.changedPaths = ['src/other.ts']; receipt.sha256 = prepareDelegationResult({ ...result(), changedPaths: receipt.changedPaths }, { ...binding, writeScope: ['src/other.ts'] }).sha256; assert.throws(() => assertDelegationResultIntegrity(receipt, binding), /outside/); });
