import * as vscode from 'vscode';
import assert from 'node:assert/strict';
import { mkdir, readFile, realpath, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { Handoff, Task, ProviderDiagnostic, SessionView, TaskFile, DiffLayer, PreparedReview, ReviewedCommit } from '../src/core/model';
import { git } from '../src/core/worktrees';
import { createHandoffWorkspace, officialProviders } from '../src/core/handoff';
import type { ProfileResources } from '../src/core/profileImport';
import { buildTaskPrompt, emptyBrief, emptyHandoffSummary } from '../src/core/taskContext';
import type { UsageSummary } from '../src/core/usage';
import type { BudgetSettings, BudgetObservation } from '../src/core/budgets';
import type { QuotaState } from '../src/core/quota';
import type { ResourceView } from '../src/core/resourceModel';
import type { ModelCatalog } from '../src/core/modelSelection';
import type { CapacityView } from '../src/core/profileCapacity';
import type { IntegrationOperation } from '../src/core/integrationModel';
async function waitFor(predicate: () => boolean | Promise<boolean>): Promise<void> {
  const deadline = Date.now() + 5000;
  while (!await predicate()) {
    if (Date.now() > deadline) throw new Error('Timed out waiting for the VS Code tab state.');
    await new Promise(resolve => setTimeout(resolve, 25));
  }
}
const managerOpen = () => vscode.window.tabGroups.all.flatMap(group => group.tabs).some(tab => tab.input instanceof vscode.TabInputWebview && tab.label === 'Hydra · Agents');
const tabIdentity = (tab: vscode.Tab, column: vscode.ViewColumn): string => {
  const input = tab.input;
  const resource = input instanceof vscode.TabInputTextDiff ? ['diff', input.original.toString(), input.modified.toString()]
    : input instanceof vscode.TabInputText ? ['text', input.uri.toString()] : ['other'];
  return JSON.stringify([column, tab.label, ...resource]);
};
async function correctCwd(task: Task): Promise<boolean> {
  try {
    const actual = await readFile(path.join(task.worktree, 'hydra-terminal-cwd.txt'), 'utf8');
    return path.relative(await realpath(actual), await realpath(task.worktree)) === '';
  } catch { return false; }
}
export async function run(): Promise<void> {
  const extension = vscode.extensions.getExtension('nico-dunlap.hydra-agent-manager');
  assert.ok(extension, 'Hydra extension is installed in the test host');
  if (process.env.HYDRA_TEST_DESKTOP) {
    assert.equal(vscode.env.appName, 'Hydra', 'The host is Hydra itself');
    const bundled = path.join(path.dirname(process.env.HYDRA_TEST_DESKTOP), 'resources', 'app', 'extensions', 'hydra-agent-manager');
    assert.equal(path.relative(await realpath(bundled), await realpath(extension.extensionPath)), '', 'Hydra features load from the app bundle rather than the source checkout');
  }
  await extension.activate();
  const repository = process.env.HYDRA_TEST_REPOSITORY;
  if (process.env.HYDRA_TEST_HANDOFF_PROVIDER) {
    const provider = process.env.HYDRA_TEST_HANDOFF_PROVIDER as 'claude' | 'codex';
    const handoff = await vscode.commands.executeCommand<Handoff>('hydra.getHandoff');
    assert.ok(handoff);
    assert.equal(handoff.task.provider, provider);
    assert.equal(handoff.task.repository, repository);
    assert.equal(vscode.workspace.workspaceFolders?.length, 1);
    assert.equal(path.relative(await realpath(vscode.workspace.workspaceFolders![0]!.uri.fsPath), await realpath(handoff.task.worktree)), '');
    assert.equal(await readFile(path.join(handoff.task.worktree, 'keep.txt'), 'utf8'), 'base\n');
    await waitFor(managerOpen);
    assert.equal(vscode.extensions.getExtension(officialProviders[provider].extensionId), undefined, 'Provider extensions are disabled for the smoke test');
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.openOfficialExtension'), /not enabled/);
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.createTask', { repository: handoff.task.worktree, title: 'Blocked', prompt: 'Blocked', provider }), /original Hydra window/);
    assert.ok(!vscode.window.terminals.some(item => item.name.startsWith('Hydra · ')));
    console.log(`PASS: ${provider} handoff loads the exact native workspace, presents instructions, and fails safely without an enabled provider.`);
    return;
  }
  if (process.env.HYDRA_TEST_RECOVERY === '1') {
    const tasks = await vscode.commands.executeCommand<Task[]>('hydra.listTasks');
    assert.equal(tasks?.length, 9, 'All task records, including selected provider models, discard preview, resources and capacity recovery, are recovered');
    const recoveredCapacityTask = tasks.find(task => task.title === 'Capacity recovery'); assert.ok(recoveredCapacityTask);
    const recoveredCapacity = await vscode.commands.executeCommand<CapacityView>('hydra.getCapacity');
    assert.equal(recoveredCapacity?.reserved, 1); assert.equal(recoveredCapacity?.owned[recoveredCapacityTask.id]?.uncertain, true);
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.startManaged', recoveredCapacityTask.id), /uncertain profile reservation/);
    await assert.rejects(readFile(path.join(recoveredCapacityTask.worktree, 'requests.jsonl')), { code: 'ENOENT' });
    console.log('PASS: native restart retains the uncertain terminal reservation and refuses a provider request until explicit absence reconciliation.');
    assert.ok(tasks.every(task => task.repository === repository && ['idle', 'interrupted'].includes(task.state)), 'No lost terminal is marked completed or running');
    for (const task of tasks) assert.equal((await readFile(path.join(task.worktree, 'keep.txt'), 'utf8')).replace(/\r\n/g, '\n'), 'base\n');
    assert.ok(!vscode.window.terminals.some(terminal => terminal.name.startsWith('Hydra · ')), 'Recovery does not relaunch providers automatically');
    assert.equal((await vscode.commands.executeCommand<QuotaState>('hydra.getQuotaState'))?.status, 'unchecked', 'Quota observations are transient and never auto-refreshed on restart');
    const budgetTask = tasks.find(task => task.title === 'Discard preview'); assert.ok(budgetTask);
    assert.equal(budgetTask.schedule?.budgetHold, true); assert.equal(budgetTask.schedule?.state, 'blocked');
    assert.deepEqual(budgetTask.schedule?.request, { type: 'followUp', prompt: 'Retained budget-held follow-up ü' });
    const recoveredBudgets = await vscode.commands.executeCommand<{ settings: BudgetSettings }>('hydra.getBudgets');
    assert.deepEqual(recoveredBudgets?.settings.tasks[budgetTask.id], [{ provider: 'codex', action: 'hold', inputOutputTokens: 16 }]);
    assert.equal((await vscode.commands.executeCommand<SessionView>('hydra.getSession', budgetTask.id))?.turns.length, 1, 'Budget-held follow-up was not submitted on restart');
    const resourceTask = tasks.find(task => task.title === 'Resource fixture'); assert.ok(resourceTask);
    const resources = await vscode.commands.executeCommand<Record<string, ResourceView>>('hydra.getResources');
    assert.equal(resources?.[resourceTask.id]?.status, 'passed'); assert.equal(resources?.[resourceTask.id]?.reserved, true);
    assert.equal(resources?.[resourceTask.id]?.config.database, `db_${resourceTask.id}`);
    assert.equal((await vscode.commands.executeCommand<SessionView>('hydra.getSession', resourceTask.id))?.turns.length, 1, 'Recovery does not rerun setup or submit a provider turn');
    const selectedModelTask = tasks.find(task => task.title === 'Selected model'); assert.ok(selectedModelTask);
    assert.deepEqual(selectedModelTask.modelSelection, { model: 'fixture-model', effort: 'high' });
    const modelHistory = await vscode.commands.executeCommand<SessionView>('hydra.getSession', selectedModelTask.id);
    assert.equal(modelHistory?.turns.length, 2); assert.deepEqual(modelHistory.turns[1]?.modelSettings?.effective, selectedModelTask.modelSelection);
    const selectedClaudeTask = tasks.find(task => task.title === 'Selected Claude model'); assert.ok(selectedClaudeTask);
    assert.deepEqual(selectedClaudeTask.modelSelection, { model: 'opus[1m]', effort: 'max' });
    const claudeHistory = await vscode.commands.executeCommand<SessionView>('hydra.getSession', selectedClaudeTask.id);
    assert.equal(claudeHistory?.turns.length, 2); assert.deepEqual(claudeHistory?.turns[1]?.modelSettings?.effective, { model: 'claude-fixture-model', effort: 'max' });
    const managedTask = tasks.find(task => task.interface === 'managed-cli' && task.provider === 'claude');
    assert.ok(managedTask?.sessionId, 'Managed session identity survives reload');
    const session = await vscode.commands.executeCommand<SessionView>('hydra.getSession', managedTask.id);
    assert.equal(session?.turns.length, 2);
    assert.equal(session.turns[0]?.text, 'Hello ü');
    assert.equal(session.turns[1]?.status, 'interrupted');
    const codexTask = tasks.find(task => task.interface === 'managed-cli' && task.provider === 'codex');
    assert.ok(codexTask?.sessionId); assert.equal(codexTask.sessionProvider, 'codex');
    const codexSession = await vscode.commands.executeCommand<SessionView>('hydra.getSession', codexTask.id);
    assert.equal(codexSession?.turns.length, 3); assert.equal(codexSession.turns[0]?.text, 'Codex ü complete');
    assert.equal(codexSession.turns[2]?.status, 'interrupted'); assert.equal(codexSession.approvals, undefined);
    const workspaces = await Promise.all((['claude', 'codex'] as const).map((provider, index) => createHandoffWorkspace(path.join(process.env.HYDRA_TEST_FIXTURE!, 'handoffs'), tasks[index]!, provider)));
    await writeFile(path.join(process.env.HYDRA_TEST_FIXTURE!, 'handoffs.json'), JSON.stringify(workspaces));
    const reviewedTask = tasks.find(task => task.title === 'Reviewed commit'); assert.ok(reviewedTask?.reviewedCommit);
    assert.equal((await git(reviewedTask.worktree, ['rev-parse', 'HEAD'])).trim(), reviewedTask.reviewedCommit.commit);
    assert.equal((await git(reviewedTask.worktree, ['rev-parse', 'HEAD^{tree}'])).trim(), reviewedTask.reviewedCommit.tree);
    console.log('PASS: fresh host recovers tasks and the exact reviewed commit without inventing completion or launching a model request.');
    return;
  }
  const document = await vscode.workspace.openTextDocument({ content: 'unsaved buffer\nkeep this selection\n', language: 'plaintext' });
  const editor = await vscode.window.showTextDocument(document, { preview: false });
  editor.selection = new vscode.Selection(1, 2, 1, 6);
  const terminal = vscode.window.createTerminal({ name: 'Hydra preservation smoke test' });
  terminal.show(true);
  const processId = await terminal.processId;
  try {
    for (let cycle = 0; cycle < 3; cycle++) {
      await vscode.commands.executeCommand('hydra.toggleMode');
      await waitFor(managerOpen);
      assert.equal(document.isClosed, false, 'Agents mode retains the unsaved document');
      assert.equal(document.getText(), 'unsaved buffer\nkeep this selection\n');
      assert.ok(vscode.window.terminals.includes(terminal), 'Agents mode retains the existing terminal');
      assert.ok(managerOpen(), 'Manager is open');
      await vscode.commands.executeCommand('hydra.toggleMode');
      await waitFor(() => !managerOpen() && vscode.window.activeTextEditor?.document === document &&
        vscode.window.activeTextEditor.selection.start.character === 2 &&
        vscode.window.activeTextEditor.selection.end.character === 6);
      assert.equal(vscode.window.activeTextEditor?.document, document, 'Editor focus is restored');
      assert.equal(vscode.window.activeTextEditor?.selection.start.character, 2);
      assert.equal(vscode.window.activeTextEditor?.selection.end.character, 6);
      assert.equal(await terminal.processId, processId, 'The terminal process is preserved');
      assert.ok(vscode.window.terminals.includes(terminal));
      assert.ok(!managerOpen(), 'Manager leaves the editor surface');
    }
    console.log('PASS: three mode cycles preserve unsaved text, selection, focus, and a live terminal process.');
    assert.ok((await vscode.commands.getCommands(true)).includes('hydra.conversation.focus'), 'Native conversation view has a focus command');
    const preservedUri = vscode.Uri.file(path.join(repository!, 'keep.txt'));
    await vscode.commands.executeCommand('vscode.diff', preservedUri, preservedUri, 'Hydra mode diff preservation', { viewColumn: vscode.ViewColumn.Beside, preview: false });
    await waitFor(() => vscode.window.tabGroups.activeTabGroup.activeTab?.input instanceof vscode.TabInputTextDiff);
    const diffTab = vscode.window.tabGroups.activeTabGroup.activeTab!;
    const diffIdentity = tabIdentity(diffTab, vscode.window.tabGroups.activeTabGroup.viewColumn);
    const groupCount = vscode.window.tabGroups.all.length;
    const nativeTabs = vscode.window.tabGroups.all.flatMap(group => group.tabs.map(tab => tabIdentity(tab, group.viewColumn)));
    await vscode.commands.executeCommand('hydra.openAgents');
    await waitFor(managerOpen);
    await vscode.commands.executeCommand('hydra.openConversation');
    await waitFor(() => {
      const group = vscode.window.tabGroups.activeTabGroup;
      return !managerOpen() && !!group.activeTab && tabIdentity(group.activeTab, group.viewColumn) === diffIdentity;
    }).catch(error => {
      console.error('Expected restored diff:', diffIdentity, 'Actual groups:', vscode.window.tabGroups.all.map(group => ({ column: group.viewColumn, active: group.isActive, tabs: group.tabs.map(tab => ({ identity: tabIdentity(tab, group.viewColumn), active: tab.isActive })) })));
      throw error;
    });
    assert.equal(vscode.window.tabGroups.all.length, groupCount, 'Mode switches preserve split groups');
    const restoredTabs = vscode.window.tabGroups.all.flatMap(group => group.tabs.map(tab => tabIdentity(tab, group.viewColumn)));
    assert.deepEqual(restoredTabs.sort(), nativeTabs.sort(), 'Mode switches preserve native tab resources, labels, and groups including the diff');
    assert.equal(await terminal.processId, processId);
    assert.ok(!vscode.window.terminals.some(item => item.name.startsWith('Hydra · ')), 'Focusing conversation makes no provider launch');
    await vscode.window.tabGroups.close(vscode.window.tabGroups.activeTabGroup.activeTab!);
    await vscode.window.showTextDocument(document, { viewColumn: vscode.ViewColumn.One, preview: false });
    console.log('PASS: Editor conversation focus and mode switches preserve native diff tabs, split groups, and terminal processes without launching a provider.');
    const workbench = vscode.workspace.getConfiguration('workbench');
    const windowConfig = vscode.workspace.getConfiguration('window');
    const previousTheme = workbench.inspect<string>('colorTheme')?.globalValue;
    const previousAutomatic = windowConfig.inspect<boolean>('autoDetectColorScheme')?.globalValue;
    try {
      await vscode.commands.executeCommand('hydra.openAgents');
      await vscode.commands.executeCommand('hydra.openSettings');
      await vscode.commands.executeCommand('hydra.openSettings');
      const settingsTabs = () => vscode.window.tabGroups.all.flatMap(group => group.tabs).filter(tab => tab.input instanceof vscode.TabInputWebview && tab.label === 'Hydra · Settings');
      await waitFor(() => settingsTabs().length === 1);
      assert.ok(managerOpen(), 'Settings retains the agent-manager tab');
      const tasksBeforeAppearance = await vscode.commands.executeCommand<Task[]>('hydra.listTasks');
      for (const mode of ['light', 'dark'] as const) {
        await vscode.commands.executeCommand('hydra.setAppearance', mode);
        await waitFor(() => vscode.window.activeColorTheme.kind === (mode === 'light' ? vscode.ColorThemeKind.Light : vscode.ColorThemeKind.Dark));
        assert.equal(vscode.workspace.getConfiguration('workbench').get('colorTheme'), mode === 'light' ? 'Hydra Light' : 'Hydra Dark');
        assert.equal(vscode.workspace.getConfiguration('window').get('autoDetectColorScheme'), false);
        assert.equal(document.getText(), 'unsaved buffer\nkeep this selection\n');
        assert.equal(document.isClosed, false, 'Appearance preserves unsaved documents');
        assert.equal(await terminal.processId, processId, 'Appearance preserves the terminal process');
        assert.deepEqual(await vscode.commands.executeCommand('hydra.listTasks'), tasksBeforeAppearance, 'Appearance does not mutate task/session records');
      }
      await assert.rejects(async () => await vscode.commands.executeCommand('hydra.setAppearance', 'unknown'), /Unknown appearance/);
      await workbench.update('colorTheme', 'Hydra Dark', vscode.ConfigurationTarget.Workspace);
      try {
        await assert.rejects(async () => await vscode.commands.executeCommand('hydra.setAppearance', 'light'), /workspace overrides/);
        assert.equal(vscode.workspace.getConfiguration('workbench').inspect<string>('colorTheme')?.globalValue, 'Hydra Dark', 'Override refusal leaves global preferences untouched');
      } finally { await workbench.update('colorTheme', undefined, vscode.ConfigurationTarget.Workspace); }
      await vscode.window.tabGroups.close(settingsTabs());
      await vscode.commands.executeCommand('hydra.toggleMode');
      await waitFor(() => !managerOpen() && vscode.window.activeTextEditor?.document === document);
      console.log('PASS: native Settings reuse, dark/light themes, override refusal, and unchanged unsaved buffers, terminal process, and task records.');
    } finally {
      await workbench.update('colorTheme', previousTheme, vscode.ConfigurationTarget.Global);
      await windowConfig.update('autoDetectColorScheme', previousAutomatic, vscode.ConfigurationTarget.Global);
    }
  } finally { terminal.dispose(); }
  if (process.env.HYDRA_TEST_DESKTOP) {
    const accountsBefore = await vscode.commands.executeCommand<Record<string,{status:string}>>('hydra.getAccountSetupState');
    assert.equal(accountsBefore?.claude?.status,'unchecked'); assert.equal(accountsBefore?.codex?.status,'unchecked');
    await vscode.commands.executeCommand('hydra.openAccounts');
    await vscode.commands.executeCommand('hydra.openAccounts');
    const accountTabs = () => vscode.window.tabGroups.all.flatMap(group => group.tabs).filter(tab => tab.input instanceof vscode.TabInputWebview && tab.label === 'Hydra · Accounts');
    await waitFor(() => accountTabs().length === 1);
    assert.deepEqual(await vscode.commands.executeCommand('hydra.getAccountSetupState'),accountsBefore,'Opening account setup is passive and never probes or starts sign-in');
    await vscode.window.tabGroups.close(accountTabs());
    assert.equal(document.isClosed,false,'Account setup preserves dirty editor documents');
    console.log('PASS: native provider account panel reuses one tab and opening it leaves provider state unchecked.');
    const setupTabs = () => vscode.window.tabGroups.all.flatMap(group => group.tabs).filter(tab => tab.input instanceof vscode.TabInputWebview && tab.label === 'Welcome to Hydra');
    assert.equal(setupTabs().length, 0, 'A built-in extension must not auto-open onboarding in an extension test host');
    const startup = await vscode.commands.executeCommand<{ development: boolean }>('hydra.desktop.startupContext');
    assert.equal(startup?.development, true, 'Owned workbench recognizes the separate native test harness');
    const setupBefore = await vscode.commands.executeCommand('hydra.getOnboardingState');
    await vscode.commands.executeCommand('hydra.openOnboarding');
    await vscode.commands.executeCommand('hydra.openOnboarding');
    await waitFor(() => setupTabs().length === 1);
    await vscode.window.tabGroups.close(setupTabs());
    assert.deepEqual(await vscode.commands.executeCommand('hydra.getOnboardingState'), setupBefore, 'Closing setup preserves the interrupted step');
    await vscode.commands.executeCommand('hydra.openOnboarding');
    await waitFor(() => setupTabs().length === 1);
    await vscode.window.tabGroups.close(setupTabs());
    assert.equal(document.isClosed, false, 'Reopening setup preserves dirty editor documents');
    console.log('PASS: native onboarding suppresses first-run in test hosts, reuses one tab, reopens its interrupted state, and preserves dirty documents.');
    const profile = await vscode.commands.executeCommand<ProfileResources>('hydra.desktop.profileResources');
    assert.ok(profile); assert.equal(profile.name, 'Hydra Native Acceptance');
    assert.notEqual(path.dirname(profile.settings), profile.root, 'Native acceptance uses a named profile rather than inferring paths from global storage');
    const defaultSettings = path.join(profile.root, 'settings.json');
    const defaultBefore = await readFile(defaultSettings).catch(error => { if (error.code === 'ENOENT') return null; throw error; });
    const source = path.join(process.env.HYDRA_TEST_FIXTURE!, 'Cursor preferences'); await mkdir(path.join(source, 'snippets'), { recursive: true });
    const sourceText = '// Imported preferences\n{"editor.fontSize":25,"editor.tabSize":3,"cursor.unavailable":true,"sample.apiKey":"never-copy","hydra.handoff":{"version":1}}\n';
    await writeFile(path.join(source, 'settings.json'), sourceText);
    await writeFile(path.join(source, 'keybindings.json'), '[{"key":"ctrl+alt+shift+9","command":"workbench.action.files.save"}]');
    await writeFile(path.join(source, 'snippets', 'typescript.json'), '{"Hydra Test":{"prefix":"hydra-test","body":"test $0"}}');
    const preview = await vscode.commands.executeCommand<{ token: string; items: { name: string; state: string }[] }>('hydra.previewImport', source); assert.ok(preview);
    assert.ok(preview.items.some(item => item.name === 'cursor.unavailable' && item.state === 'skip'));
    assert.ok(preview.items.some(item => item.name === 'hydra.handoff' && item.state === 'skip'));
    const preferenceDocument = await vscode.workspace.openTextDocument(vscode.Uri.file(profile.settings));
    await vscode.window.showTextDocument(preferenceDocument);
    const pending = new vscode.WorkspaceEdit(); pending.insert(preferenceDocument.uri, new vscode.Position(0, 0), '// Unsaved preferences\n'); assert.equal(await vscode.workspace.applyEdit(pending), true);
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.applyImport', preview.token, ['settings']), /unsaved preference/);
    await vscode.commands.executeCommand('workbench.action.revertAndCloseActiveEditor');
    assert.equal(await vscode.commands.executeCommand('hydra.applyImport', preview.token, ['settings', 'keybindings', 'snippets']), 3);
    assert.equal(vscode.workspace.getConfiguration('hydra').inspect('handoff')?.globalValue, undefined);
    await waitFor(() => vscode.workspace.getConfiguration('editor').inspect<number>('fontSize')?.globalValue === 25);
    assert.equal(await readFile(path.join(source, 'settings.json'), 'utf8'), sourceText);
    assert.equal(await readFile(path.join(profile.snippets, 'typescript.json'), 'utf8').then(text => text.includes('Hydra Test')), true);
    await vscode.commands.executeCommand('hydra.undoImport');
    await waitFor(() => vscode.workspace.getConfiguration('editor').inspect<number>('fontSize')?.globalValue === undefined);
    assert.deepEqual(await readFile(defaultSettings).catch(error => { if (error.code === 'ENOENT') return null; throw error; }), defaultBefore);
    assert.equal(document.isClosed, false); assert.equal(document.getText(), 'unsaved buffer\nkeep this selection\n');
    console.log('PASS: native named-profile import, credential/unavailable-setting skips, unsaved-preference refusal, configuration reload, undo, and unchanged default profile/source/unsaved text.');
  } else {
    const importStatus = await vscode.commands.executeCommand<{ available: boolean }>('hydra.getImportStatus'); assert.equal(importStatus?.available, false);
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.previewImport', path.join(process.env.HYDRA_TEST_FIXTURE!, 'not-a-profile')), /local Hydra desktop/);
    console.log('PASS: importing is unavailable in the VS Code development host.');
  }
  if (repository && process.env.HYDRA_TEST_PROVIDER) {
    const config = vscode.workspace.getConfiguration('hydra');
    await config.update('claudePath', process.env.HYDRA_TEST_PROVIDER, vscode.ConfigurationTarget.Workspace);
    await config.update('codexPath', process.env.HYDRA_TEST_CODEX_PROVIDER, vscode.ConfigurationTarget.Workspace);
    await config.update('maxConcurrentTasks', 2, vscode.ConfigurationTarget.Workspace);
    const diagnostic = await vscode.commands.executeCommand<ProviderDiagnostic>('hydra.checkProvider', 'claude');
    assert.equal(diagnostic?.status, 'checked'); assert.equal(diagnostic.version, '2.1.270');
    const probeCalls = (await readFile(path.join(repository, 'hydra-probes.jsonl'), 'utf8')).trim().split('\n').map(line => JSON.parse(line));
    assert.deepEqual(probeCalls, [['--version'], ['--help']], 'Capability checks do not start a session or submit a prompt');
    assert.ok(!vscode.window.terminals.some(item => item.name.startsWith('Hydra · ')), 'Checks do not launch provider terminals');
    console.log('PASS: explicit capability checks read only version/help and retain advertised options without claiming managed-session support.');
    const tasks: Task[] = [];
    for (const provider of ['claude', 'codex', 'codex']) {
      const task = await vscode.commands.executeCommand<Task>('hydra.createTask', { repository, provider, title: `Smoke ${provider} ${tasks.length + 1}`, prompt: 'Test launch mechanics only; do not call a model.' });
      assert.ok(task);
      tasks.push(task);
    }
    assert.equal(new Set(tasks.map(task => task.worktree)).size, 3);
    const draftTask = tasks[0]!;
    await vscode.commands.executeCommand('hydra.saveConversationDraft', draftTask.id, 'Preserve across modes', 'smoke-draft-1');
    await vscode.commands.executeCommand('hydra.openTask', draftTask.id);
    await vscode.commands.executeCommand('hydra.openConversation');
    const conversationState = () => vscode.commands.executeCommand<{ mode: string; selectedId: string; draft?: { prompt: string; version: string } }>('hydra.getConversationState');
    assert.equal((await conversationState())?.draft?.prompt, 'Preserve across modes');
    await vscode.commands.executeCommand('hydra.openAgents');
    await vscode.commands.executeCommand('hydra.openConversation');
    assert.equal((await conversationState())?.selectedId, draftTask.id);
    assert.equal((await conversationState())?.draft?.version, 'smoke-draft-1');
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.followUp', draftTask.id, 'Preserve across modes', 'smoke-draft-1'), /Start the task/);
    assert.equal((await conversationState())?.draft?.prompt, 'Preserve across modes', 'Rejected submission preserves the draft');
    assert.equal((await vscode.commands.executeCommand<SessionView>('hydra.getSession', draftTask.id))?.turns.length || 0, 0, 'Draft edits and mode switches do not submit a turn');
    console.log('PASS: shared conversation draft survives surface switches and a rejected follow-up without a provider turn.');
    const brief = { ...emptyBrief(), goal: 'Test launch mechanics only; do not call a model.', constraints: 'Literal $(text) stays data.', relevantPaths: 'keep.txt', acceptance: 'Fake provider receives this exact prompt.' };
    await vscode.commands.executeCommand('hydra.saveBrief', tasks[0]!.id, brief);
    const submittedPrompt = buildTaskPrompt(brief);
    assert.equal((await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === tasks[0]!.id)?.prompt, submittedPrompt);
    await vscode.commands.executeCommand('hydra.saveHandoffSummary', tasks[0]!.id, { ...emptyHandoffSummary(), summary: 'Local fixture handoff', validation: 'No provider call for this action.', evidenceRefs: 'keep.txt' });
    await vscode.commands.executeCommand('hydra.showTaskHandoff', tasks[0]!.id);
    assert.ok(vscode.window.activeTextEditor?.document.getText().includes('Local fixture handoff'));
    assert.ok(vscode.window.activeTextEditor?.document.getText().includes('No reviewed commit'));
    const handoffDocument = vscode.window.activeTextEditor!.document;
    const savedHandoff = await readFile(handoffDocument.uri.fsPath, 'utf8');
    const handoffEdit = new vscode.WorkspaceEdit(); handoffEdit.insert(handoffDocument.uri, new vscode.Position(0, 0), 'Unsaved local handoff note\n');
    assert.equal(await vscode.workspace.applyEdit(handoffEdit), true);
    const dirtyHandoff = handoffDocument.getText();
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.showTaskHandoff', tasks[0]!.id), /unsaved generated handoff/);
    assert.equal(handoffDocument.getText(), dirtyHandoff); assert.equal(handoffDocument.isDirty, true);
    assert.equal(await readFile(handoffDocument.uri.fsPath, 'utf8'), savedHandoff);
    await vscode.window.showTextDocument(handoffDocument);
    await vscode.commands.executeCommand('workbench.action.revertAndCloseActiveEditor');
    await vscode.workspace.getConfiguration('hydra').update('maxConcurrentTasks', 4, vscode.ConfigurationTarget.Workspace);
    for (const task of tasks.slice(0, 2)) await vscode.commands.executeCommand('hydra.launchTask', task.id);
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.saveBrief', tasks[0]!.id, brief), /locked after launch/);
    for (const task of tasks.slice(0, 2)) {
      await waitFor(() => correctCwd(task));
    }
    assert.equal(vscode.window.terminals.filter(item => item.name.startsWith('Hydra · ')).length, 2);
    const terminalCapacity = await vscode.commands.executeCommand<CapacityView>('hydra.getCapacity');
    assert.equal(terminalCapacity?.reserved, 2, 'Native terminals consume durable profile slots');
    assert.equal(terminalCapacity?.limit, 2); assert.equal(Object.keys(terminalCapacity.owned).length, 2);
    await vscode.commands.executeCommand('hydra.launchTask', tasks[2]!.id);
    assert.equal((await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === tasks[2]!.id)?.schedule?.state, 'queued');
    assert.equal((await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === tasks[2]!.id)?.schedule?.reason, 'Waiting for a shared profile slot.', 'Profile slots enforce the limit independently of the four-slot window limit');
    await vscode.workspace.getConfiguration('hydra').update('maxConcurrentTasks', 2, vscode.ConfigurationTarget.Workspace);
    const queuedBriefTask = (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === tasks[2]!.id);
    assert.ok(queuedBriefTask?.contextLockedAt, 'Queued launch records its brief lock before dispatch');
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.saveBrief', tasks[2]!.id, { ...brief, goal: 'Changed queued goal' }), /locked after launch/);
    assert.equal((await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === tasks[2]!.id)?.prompt, queuedBriefTask.prompt, 'Rejected queued edit preserves the exact prompt');
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.prepareIntegration', tasks[2]!.id, [{ executable: 'node', args: ['--version'] }]), /Cancel queued work/);
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.openDiff', tasks[2]!.id, 'keep.txt', 'combined'), /Stop this task writer/);
    await vscode.commands.executeCommand('hydra.launchTask', tasks[0]!.id);
    assert.equal(vscode.window.terminals.filter(item => item.name.startsWith('Hydra · ')).length, 2, 'Duplicate launch reveals the existing terminal');
    const pids = await Promise.all(vscode.window.terminals.filter(item => item.name.startsWith('Hydra · ')).map(item => item.processId));
    await vscode.commands.executeCommand('hydra.openAgents');
    await waitFor(managerOpen);
    await vscode.commands.executeCommand('hydra.toggleMode');
    await waitFor(() => !managerOpen());
    assert.deepEqual(await Promise.all(vscode.window.terminals.filter(item => item.name.startsWith('Hydra · ')).map(item => item.processId)), pids);
    await vscode.commands.executeCommand('hydra.stopTask', tasks[0]!.id);
    await waitFor(async () => (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === tasks[0]!.id)?.state === 'interrupted');
    await waitFor(() => correctCwd(tasks[2]!));
    console.log('PASS: both provider routes launch in exact worktrees, reuse terminals, enforce the two-terminal limit, and survive mode changes.');
    for (const task of tasks.slice(1)) await vscode.commands.executeCommand('hydra.stopTask', task.id);
    await waitFor(async () => (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.filter(task => tasks.slice(1).some(item => item.id === task.id)).every(task => !['queued', 'starting', 'running'].includes(task.schedule?.state || '')) || false);
    await waitFor(async () => (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.every(task => task.state === 'interrupted') || false);
    await waitFor(async () => (await vscode.commands.executeCommand<CapacityView>('hydra.getCapacity'))?.reserved === 0);
    await vscode.commands.executeCommand('hydra.startManaged', tasks[0]!.id);
    await waitFor(async () => { const session = await vscode.commands.executeCommand<SessionView>('hydra.getSession', tasks[0]!.id); return session?.turns[0]?.status === 'completed' && !session.active; });
    const completed = await vscode.commands.executeCommand<SessionView>('hydra.getSession', tasks[0]!.id);
    assert.equal(completed?.turns[0]?.text, 'Hello ü');
    assert.equal(completed.turns[0]?.usage?.input, 12);
    const plannerRun = (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === tasks[0]!.id)?.delegationPlanner;
    // Auto is paused (Official_Extensions_Plan Phase 0): a Solo turn saves no planner run and
    // the provider receives exactly the brief, with no planning suffix.
    assert.equal(plannerRun, undefined, 'Solo turn saves no planner receipt');
    const normalTurnPrompt = submittedPrompt;
    assert.equal(completed.turns[0]?.prompt, normalTurnPrompt);
    const reported = await vscode.commands.executeCommand<{ tasks: Record<string, UsageSummary> }>('hydra.getUsage');
    assert.equal(reported?.tasks[tasks[0]!.id]?.claude?.input, 12);
    await vscode.commands.executeCommand('hydra.saveConversationDraft', tasks[0]!.id, 'hold', 'smoke-accepted-1');
    await vscode.commands.executeCommand('hydra.followUp', tasks[0]!.id, 'hold', 'smoke-accepted-1');
    assert.equal((await conversationState())?.draft?.prompt, '', 'Accepted queued follow-up consumes its exact draft');
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.followUp', tasks[0]!.id, 'hold', 'smoke-accepted-1'), /already submitted|in progress/);
    await waitFor(async () => { try { await readFile(path.join(tasks[0]!.worktree, 'heartbeat.txt')); return true; } catch { return false; } });
    const requests = (await readFile(path.join(tasks[0]!.worktree, 'requests.jsonl'), 'utf8')).trim().split('\n').map(line => JSON.parse(line));
    assert.equal(requests[0].prompt, normalTurnPrompt, 'The provider receives exactly the saved brief in one normal turn');
    assert.equal(requests.length, 2);
    assert.equal(requests[1].args[requests[1].args.indexOf('--resume') + 1], '12345678-1234-1234-1234-123456789abc');
    assert.equal(path.relative(await realpath(requests[0].cwd), await realpath(tasks[0]!.worktree)), '');
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.launchTask', tasks[0]!.id), /managed process/);
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.handoffCodex', tasks[0]!.id), /managed process/);
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.openDiff', tasks[0]!.id, 'keep.txt', 'combined'), /Stop this task writer/);
    await vscode.commands.executeCommand('hydra.launchTask', tasks[1]!.id);
    await vscode.commands.executeCommand('hydra.launchTask', tasks[2]!.id);
    assert.equal((await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === tasks[2]!.id)?.schedule?.state, 'queued');
    await vscode.commands.executeCommand('hydra.stopTask', tasks[0]!.id);
    assert.equal((await vscode.commands.executeCommand<SessionView>('hydra.getSession', tasks[0]!.id))?.turns[1]?.status, 'interrupted');
    await waitFor(() => correctCwd(tasks[2]!));
    console.log('PASS: managed Claude streams and persists a result, resumes its explicit ID, blocks overlapping writers, shares concurrency with terminals, and stops without inventing completion.');
    for (const task of tasks.slice(1)) await vscode.commands.executeCommand('hydra.stopTask', task.id);
    await waitFor(async () => (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.every(task => task.state === 'interrupted') || false);
    await vscode.commands.executeCommand('hydra.startManaged', tasks[1]!.id);
    await waitFor(async () => { const session = await vscode.commands.executeCommand<SessionView>('hydra.getSession', tasks[1]!.id); return session?.turns[0]?.status === 'completed' && !session.active; });
    assert.equal((await vscode.commands.executeCommand<SessionView>('hydra.getSession', tasks[1]!.id))?.turns[0]?.text, 'Codex ü complete');
    await vscode.commands.executeCommand('hydra.followUp', tasks[1]!.id, 'approval');
    await waitFor(async () => !!(await vscode.commands.executeCommand<SessionView>('hydra.getSession', tasks[1]!.id))?.approvals?.length);
    await waitFor(async () => (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === tasks[1]!.id)?.schedule?.state === 'waiting-for-approval');
    const pending = await vscode.commands.executeCommand<SessionView>('hydra.getSession', tasks[1]!.id);
    const approvalId = pending!.approvals![0]!.id;
    await vscode.commands.executeCommand('hydra.approve', tasks[1]!.id, approvalId, 'accept');
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.approve', tasks[1]!.id, approvalId, 'accept'), /no longer pending|No active/);
    await waitFor(async () => { const session = await vscode.commands.executeCommand<SessionView>('hydra.getSession', tasks[1]!.id); return session?.turns[1]?.status === 'completed' && !session.active; });
    await vscode.commands.executeCommand('hydra.followUp', tasks[1]!.id, 'hold');
    await waitFor(async () => (await vscode.commands.executeCommand<SessionView>('hydra.getSession', tasks[1]!.id))?.turns[2]?.text === 'Streaming ü');
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.launchTask', tasks[1]!.id), /managed process/);
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.handoffClaude', tasks[1]!.id), /managed process/);
    await vscode.commands.executeCommand('hydra.launchTask', tasks[2]!.id);
    await vscode.commands.executeCommand('hydra.launchTask', tasks[0]!.id);
    assert.equal((await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === tasks[0]!.id)?.schedule?.state, 'queued');
    await vscode.commands.executeCommand('hydra.cancelQueued', tasks[0]!.id);
    assert.equal((await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === tasks[0]!.id)?.schedule?.state, 'cancelled');
    await vscode.commands.executeCommand('hydra.stopTask', tasks[1]!.id);
    await vscode.commands.executeCommand('hydra.stopTask', tasks[2]!.id);
    assert.equal((await vscode.commands.executeCommand<SessionView>('hydra.getSession', tasks[1]!.id))?.turns[2]?.status, 'interrupted');
    const codexRequests = (await readFile(path.join(tasks[1]!.worktree, 'codex-requests.jsonl'), 'utf8')).trim().split('\n').map(line => JSON.parse(line));
    assert.equal(codexRequests.find(message => message.method === 'thread/resume').params.threadId, '12345678-1234-7234-9234-123456789abc');
    assert.ok(codexRequests.find(message => message.method === 'turn/interrupt'));
    console.log('PASS: managed Codex streams, resumes its explicit thread, routes one approval, rejects stale approvals and overlapping writers, shares concurrency, and interrupts the active turn.');
    const reviewTask = tasks[2]!;
    const claudeRequestsBefore = await readFile(path.join(tasks[0]!.worktree, 'requests.jsonl'), 'utf8');
    const codexRequestsBefore = await readFile(path.join(tasks[1]!.worktree, 'codex-requests.jsonl'), 'utf8');
    await writeFile(path.join(reviewTask.worktree, 'review.txt'), 'committed review\n');
    await writeFile(path.join(reviewTask.worktree, 'old review.txt'), 'rename review\n');
    await writeFile(path.join(reviewTask.worktree, 'deleted review.txt'), 'deletion review\n');
    await git(reviewTask.worktree, ['add', 'review.txt', 'old review.txt', 'deleted review.txt']);
    await git(reviewTask.worktree, ['commit', '-m', 'review fixture']);
    await git(reviewTask.worktree, ['mv', 'old review.txt', 'renamed review ü.txt']);
    await writeFile(path.join(reviewTask.worktree, 'review.txt'), 'staged review\n'); await git(reviewTask.worktree, ['add', 'review.txt']);
    await writeFile(path.join(reviewTask.worktree, 'review.txt'), 'saved review\n');
    const fs = await import('node:fs/promises'); await fs.rm(path.join(reviewTask.worktree, 'deleted review.txt'));
    await writeFile(path.join(reviewTask.worktree, 'untracked review.txt'), 'untracked review\n');
    await writeFile(path.join(reviewTask.worktree, 'binary review.bin'), Buffer.from([0, 1, 255]));
    const editDocument = await vscode.workspace.openTextDocument(path.join(reviewTask.worktree, 'review.txt'));
    const unsaved = new vscode.WorkspaceEdit(); unsaved.insert(editDocument.uri, new vscode.Position(0, 0), 'unsaved editor change\n');
    assert.equal(await vscode.workspace.applyEdit(unsaved), true); assert.equal(editDocument.isDirty, true);
    const statusBefore = await git(reviewTask.worktree, ['status', '--porcelain=v1', '-z']);
    await vscode.commands.executeCommand('hydra.openAgents');
    const changes = await vscode.commands.executeCommand<TaskFile[]>('hydra.getChanges', reviewTask.id);
    assert.ok(changes?.find(file => file.path === 'review.txt')?.changes?.some(change => change.layer === 'staged'));
    for (const [file, layer, left, right] of [
      ['review.txt', 'combined', '', 'saved review\n'], ['review.txt', 'committed', '', 'committed review\n'],
      ['review.txt', 'staged', 'committed review\n', 'staged review\n'], ['review.txt', 'unstaged', 'staged review\n', 'saved review\n'],
      ['renamed review ü.txt', 'staged', 'rename review\n', 'rename review\n'], ['deleted review.txt', 'unstaged', 'deletion review\n', ''],
      ['untracked review.txt', 'untracked', '', 'untracked review\n']
    ] as [string, DiffLayer, string, string][]) {
      await vscode.commands.executeCommand('hydra.openDiff', reviewTask.id, file, layer);
      const input = vscode.window.tabGroups.activeTabGroup.activeTab?.input;
      assert.ok(input instanceof vscode.TabInputTextDiff, 'Text changes open an actual native diff tab');
      assert.equal(input.original.scheme, 'hydra-review'); assert.equal(input.modified.scheme, 'hydra-review');
      assert.equal((await vscode.workspace.openTextDocument(input.original)).getText(), left);
      assert.equal((await vscode.workspace.openTextDocument(input.modified)).getText(), right);
      assert.ok(managerOpen(), 'Native review leaves the manager open');
      if (layer === 'unstaged' && file === 'review.txt') {
        await writeFile(path.join(reviewTask.worktree, 'review.txt'), 'later saved review\n');
        assert.equal((await vscode.workspace.openTextDocument(input.modified)).getText(), right, 'Snapshot does not silently update after disk edits');
      }
    }
    await vscode.commands.executeCommand('hydra.openDiff', reviewTask.id, 'binary review.bin', 'untracked');
    const binaryInput = vscode.window.tabGroups.activeTabGroup.activeTab?.input;
    assert.ok(binaryInput instanceof vscode.TabInputText, 'Binary review opens a native metadata document instead of a text diff');
    assert.ok((await vscode.workspace.openTextDocument(binaryInput.uri)).getText().includes('No text diff generated'));
    assert.equal(editDocument.isDirty, true); assert.ok(editDocument.getText().startsWith('unsaved editor change\n'), 'Review preserves the unsaved live editor');
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.prepareCommitReview', reviewTask.id), /unsaved task editor buffers/);
    assert.equal(await git(reviewTask.worktree, ['status', '--porcelain=v1', '-z']), statusBefore);
    assert.equal(await readFile(path.join(tasks[0]!.worktree, 'requests.jsonl'), 'utf8'), claudeRequestsBefore);
    assert.equal(await readFile(path.join(tasks[1]!.worktree, 'codex-requests.jsonl'), 'utf8'), codexRequestsBefore);
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.openDiff', reviewTask.id, '../../keep.txt', 'unstaged'), /relative/);
    console.log('PASS: native read-only diff tabs show committed/staged/unstaged/untracked/renamed/deleted snapshots, preserve dirty buffers, show binary metadata, and make zero provider requests.');
    const commitTask = await vscode.commands.executeCommand<Task>('hydra.createTask', { repository, provider: 'codex', title: 'Reviewed commit', prompt: 'Local Git review only; no model request.' });
    assert.ok(commitTask);
    await writeFile(path.join(commitTask.worktree, 'commit review ü.txt'), 'fixed staged review\n'); await git(commitTask.worktree, ['add', '-A']);
    const prepared = await vscode.commands.executeCommand<PreparedReview>('hydra.prepareCommitReview', commitTask.id); assert.ok(prepared);
    await vscode.commands.executeCommand('hydra.openCommitReview', commitTask.id, prepared.token, 'commit review ü.txt');
    const preparedTab = vscode.window.tabGroups.activeTabGroup.activeTab?.input; assert.ok(preparedTab instanceof vscode.TabInputTextDiff);
    assert.equal((await vscode.workspace.openTextDocument(preparedTab.modified)).getText(), 'fixed staged review\n');
    await writeFile(path.join(commitTask.worktree, 'commit review ü.txt'), 'stale saved edit\n');
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.commitReviewed', commitTask.id, prepared.token, 'Reviewed commit'), /Stage all/);
    assert.equal((await git(commitTask.worktree, ['rev-parse', 'HEAD'])).trim(), commitTask.baseCommit);
    await git(commitTask.worktree, ['add', '-A']);
    const fresh = await vscode.commands.executeCommand<PreparedReview>('hydra.prepareCommitReview', commitTask.id); assert.ok(fresh);
    const receipt = await vscode.commands.executeCommand<ReviewedCommit>('hydra.commitReviewed', commitTask.id, fresh.token, 'Reviewed task commit'); assert.ok(receipt);
    assert.equal(receipt.tree, fresh.tree); assert.equal((await git(commitTask.worktree, ['rev-parse', 'HEAD'])).trim(), receipt.commit);
    assert.equal(await git(commitTask.worktree, ['status', '--porcelain=v1']), '');
    assert.equal((await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === commitTask.id)?.reviewedCommit?.commit, receipt.commit);
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.commitReviewed', commitTask.id, fresh.token, 'Duplicate'), /Review expired/);
    assert.equal(editDocument.isDirty, true); assert.equal(await readFile(path.join(tasks[0]!.worktree, 'requests.jsonl'), 'utf8'), claudeRequestsBefore); assert.equal(await readFile(path.join(tasks[1]!.worktree, 'codex-requests.jsonl'), 'utf8'), codexRequestsBefore);
    console.log('PASS: native prepared review uses fixed Git objects, refuses dirty buffers and stale state, records the exact reviewed commit, and makes zero provider requests.');
    const modelTask = await vscode.commands.executeCommand<Task>('hydra.createTask', { repository, provider: 'codex', title: 'Selected model', prompt: 'Fixture model controls only.' }); assert.ok(modelTask);
    const catalog = await vscode.commands.executeCommand<ModelCatalog>('hydra.checkModels', modelTask.id); assert.equal(catalog?.status, 'ready');
    assert.equal(catalog.models[0]?.model, 'fixture-model');
    const metadataRequests = (await readFile(path.join(modelTask.worktree, 'codex-requests.jsonl'), 'utf8')).trim().split('\n').map(line => JSON.parse(line));
    assert.deepEqual(metadataRequests.map(request => request.method), ['initialize', 'initialized', 'model/list']);
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.saveModelSelection', modelTask.id, { model: 'gpt-6-astra', effort: 'high' }), /does not currently advertise/);
    const selection = { model: 'fixture-model', effort: 'high' };
    await vscode.commands.executeCommand('hydra.saveModelSelection', modelTask.id, selection);
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.launchTask', modelTask.id), /explicit managed Codex/);
    await vscode.commands.executeCommand('hydra.startManaged', modelTask.id);
    await waitFor(async () => { const view = await vscode.commands.executeCommand<SessionView>('hydra.getSession', modelTask.id); return view?.turns[0]?.status === 'completed' && !view.active; });
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.saveModelSelection', modelTask.id, null), /locked after launch/);
    await vscode.commands.executeCommand('hydra.followUp', modelTask.id, 'Resume with the saved fixture settings.');
    await waitFor(async () => { const view = await vscode.commands.executeCommand<SessionView>('hydra.getSession', modelTask.id); return view?.turns[1]?.status === 'completed' && !view.active; });
    const modelView = await vscode.commands.executeCommand<SessionView>('hydra.getSession', modelTask.id);
    assert.deepEqual(modelView?.turns[1]?.modelSettings, { requested: selection, effective: selection });
    console.log('PASS: native model discovery submits no prompt, unsupported Astra is refused, explicit settings lock, and acknowledged model/effort survive resume.');
    const claudeModelTask = await vscode.commands.executeCommand<Task>('hydra.createTask', { repository, provider: 'claude', title: 'Selected Claude model', prompt: 'Fixture Claude controls only.' }); assert.ok(claudeModelTask);
    const claudeCatalog = await vscode.commands.executeCommand<ModelCatalog>('hydra.checkModels', claudeModelTask.id); assert.equal(claudeCatalog?.status, 'ready');
    await assert.rejects(readFile(path.join(claudeModelTask.worktree, 'requests.jsonl')), { code: 'ENOENT' });
    const claudeSelection = { model: 'opus[1m]', effort: 'max' };
    await vscode.commands.executeCommand('hydra.saveModelSelection', claudeModelTask.id, claudeSelection);
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.launchTask', claudeModelTask.id), /explicit managed Claude/);
    await vscode.commands.executeCommand('hydra.startManaged', claudeModelTask.id);
    await waitFor(async () => { const view = await vscode.commands.executeCommand<SessionView>('hydra.getSession', claudeModelTask.id); return view?.turns[0]?.status === 'completed' && !view.active; });
    await vscode.commands.executeCommand('hydra.followUp', claudeModelTask.id, 'approve:Bash');
    await waitFor(async () => !!(await vscode.commands.executeCommand<SessionView>('hydra.getSession', claudeModelTask.id))?.approvals?.length);
    await waitFor(async () => (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === claudeModelTask.id)?.schedule?.state === 'waiting-for-approval');
    const claudeApproval = (await vscode.commands.executeCommand<SessionView>('hydra.getSession', claudeModelTask.id))!.approvals![0]!;
    await vscode.commands.executeCommand('hydra.approve', claudeModelTask.id, claudeApproval.id, 'accept');
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.approve', claudeModelTask.id, claudeApproval.id, 'accept'), /no longer pending|No active/);
    await waitFor(async () => { const view = await vscode.commands.executeCommand<SessionView>('hydra.getSession', claudeModelTask.id); return view?.turns[1]?.status === 'completed' && !view.active; });
    const nativeClaude = await vscode.commands.executeCommand<SessionView>('hydra.getSession', claudeModelTask.id);
    assert.deepEqual(nativeClaude?.turns[1]?.modelSettings, { requested: claudeSelection, effective: { model: 'claude-fixture-model', effort: 'max' } });
    const claudeDecision = JSON.parse((await readFile(path.join(claudeModelTask.worktree, 'claude-decisions.jsonl'), 'utf8')).trim()).response.response;
    assert.equal(claudeDecision.behavior, 'allow'); assert.equal(claudeDecision.updatedPermissions, undefined);
    console.log('PASS: native Claude metadata sends no prompt, canonical model/effort survives explicit resume and a scoped approval, stale consent is refused, and no persistent rule is written.');
    const targetFile=path.join(repository,'keep.txt'),targetBytes=await readFile(targetFile),targetBefore=(await git(repository,['rev-parse','HEAD'])).trim();
    const checks=[{executable:'git',args:['diff','--check',commitTask.baseCommit,'HEAD']}];
    await assert.rejects(async()=>await vscode.commands.executeCommand('hydra.prepareIntegration',commitTask.id,checks),/clean saved/);
    try{
      await git(repository,['restore','keep.txt']);
      const candidate=await vscode.commands.executeCommand<IntegrationOperation>('hydra.prepareIntegration',commitTask.id,checks);assert.ok(candidate);assert.equal(candidate.phase,'validated');assert.equal((await git(repository,['rev-parse','HEAD'])).trim(),targetBefore);
      await vscode.commands.executeCommand('hydra.openIntegrationDiff',commitTask.id,candidate.id,'commit review ü.txt');
      const integrationTab=vscode.window.tabGroups.activeTabGroup.activeTab?.input;assert.ok(integrationTab instanceof vscode.TabInputTextDiff);assert.equal((await vscode.workspace.openTextDocument(integrationTab.modified)).getText(),'stale saved edit\n');
      await vscode.commands.executeCommand('hydra.promoteIntegration',commitTask.id,candidate.id);assert.equal((await git(repository,['rev-parse','HEAD'])).trim(),candidate.candidateCommit);assert.equal((await git(repository,['rev-parse',`refs/hydra/integration-backups/${candidate.id}`])).trim(),targetBefore);assert.equal((await git(commitTask.worktree,['rev-parse','HEAD'])).trim(),receipt.commit);assert.equal(await readFile(path.join(repository,'commit review ü.txt'),'utf8'),'stale saved edit\n');assert.equal(editDocument.isDirty,true);
    }finally{await writeFile(targetFile,targetBytes);}
    assert.equal(await readFile(path.join(tasks[0]!.worktree,'requests.jsonl'),'utf8'),claudeRequestsBefore);assert.equal(await readFile(path.join(tasks[1]!.worktree,'codex-requests.jsonl'),'utf8'),codexRequestsBefore);
    console.log('PASS: native integration refuses dirty target, reviews immutable candidate diff, runs explicit checks and promotes through owning checkout with retained task and rollback reference, without provider requests.');
    const discardTask = await vscode.commands.executeCommand<Task>('hydra.createTask', { repository, provider: 'codex', title: 'Discard preview', prompt: 'Local discard review only.' }); assert.ok(discardTask);
    await writeFile(path.join(discardTask.worktree, 'discard ü.txt'), 'retained\n');
    const discardDocument = await vscode.workspace.openTextDocument(vscode.Uri.file(path.join(discardTask.worktree, 'discard ü.txt'))), discardEditor = await vscode.window.showTextDocument(discardDocument);
    await discardEditor.edit(builder => builder.insert(new vscode.Position(0, 0), 'unsaved '));
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.prepareDiscard', discardTask.id), /unsaved task editor buffers/);
    assert.equal(discardDocument.isDirty, true); await discardDocument.save();
    const discardReview = await vscode.commands.executeCommand<{ token: string; changes: { path: string }[]; head: string }>('hydra.prepareDiscard', discardTask.id); assert.ok(discardReview);
    assert.deepEqual(discardReview.changes.map(file => file.path), ['discard ü.txt']); assert.equal(discardReview.head, discardTask.baseCommit);
    await assert.rejects(async () => vscode.commands.executeCommand('hydra.confirmDiscard', discardTask.id, '0'.repeat(24)), /review expired/);
    assert.equal((await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === discardTask.id)?.state, 'idle');
    assert.equal(await readFile(path.join(discardTask.worktree, 'discard ü.txt'), 'utf8'), 'unsaved retained\n');
    assert.equal(await readFile(path.join(tasks[0]!.worktree, 'requests.jsonl'), 'utf8'), claudeRequestsBefore); assert.equal(await readFile(path.join(tasks[1]!.worktree, 'codex-requests.jsonl'), 'utf8'), codexRequestsBefore);
    console.log('PASS: native discard review preserves unsaved buffers, inventories the saved exact checkout, refuses expired tokens and makes zero provider requests. Modal confirmation and restore persistence are covered by separate real-Git tests.');
    const projectBudget = [{ provider: 'codex', action: 'hold', inputOutputTokens: 16 }];
    await vscode.commands.executeCommand('hydra.saveBudgets', discardTask.id, 'project', projectBudget);
    await vscode.commands.executeCommand('hydra.startManaged', discardTask.id);
    let held = (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === discardTask.id);
    assert.equal(held?.schedule?.budgetHold, true); assert.equal(held?.schedule?.state, 'blocked');
    await assert.rejects(readFile(path.join(discardTask.worktree, 'codex-requests.jsonl')), { code: 'ENOENT' });
    const budgetSnapshot = await vscode.commands.executeCommand<{ settings: BudgetSettings; observations: Record<string, BudgetObservation[]> }>('hydra.getBudgets');
    assert.ok(budgetSnapshot?.observations[discardTask.id]?.some(item => item.scope === 'project' && item.provider === 'codex' && item.reached));
    await vscode.commands.executeCommand('hydra.saveBudgets', discardTask.id, 'project', [{ ...projectBudget[0], action: 'warn' }]);
    held = (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === discardTask.id);
    assert.equal(held?.schedule?.budgetHold, true, 'Budget edit never automatically releases held work');
    await vscode.commands.executeCommand('hydra.retryBudgetHold', discardTask.id);
    await waitFor(async () => (await vscode.commands.executeCommand<SessionView>('hydra.getSession', discardTask.id))?.turns[0]?.status === 'completed');
    await waitFor(async () => (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === discardTask.id)?.schedule?.state === 'finished');
    const allowed = (await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === discardTask.id);
    assert.ok(allowed?.schedule?.budgetWarnings?.length, 'Warning permits the configured work and remains visible');
    await vscode.commands.executeCommand('hydra.saveBudgets', discardTask.id, 'project', []);
    await vscode.commands.executeCommand('hydra.saveBudgets', discardTask.id, 'task', [{ provider: 'codex', action: 'hold', inputOutputTokens: 16 }]);
    const requestsBeforeHold = await readFile(path.join(discardTask.worktree, 'codex-requests.jsonl'), 'utf8');
    await vscode.commands.executeCommand('hydra.followUp', discardTask.id, 'Retained budget-held follow-up ü');
    assert.equal(await readFile(path.join(discardTask.worktree, 'codex-requests.jsonl'), 'utf8'), requestsBeforeHold);
    assert.equal((await vscode.commands.executeCommand<Task[]>('hydra.listTasks'))?.find(task => task.id === discardTask.id)?.schedule?.budgetHold, true);
    console.log('PASS: native soft budgets hold unmeasured new tasks using reported project usage, retain exact follow-ups without provider requests, require explicit retry, allow warnings, and retain settings/holds for restart.');
    if (process.env.HYDRA_TEST_DESKTOP) {
      const quotasBefore = await vscode.commands.executeCommand<QuotaState>('hydra.getQuotaState');
      const tasksBeforeQuota = await vscode.commands.executeCommand<Task[]>('hydra.listTasks');
      const historyBeforeQuota = await vscode.commands.executeCommand<SessionView>('hydra.getSession', discardTask.id);
      await vscode.commands.executeCommand('hydra.openQuotaStatus');
      await waitFor(() => vscode.window.tabGroups.all.flatMap(group => group.tabs).some(tab => tab.input instanceof vscode.TabInputWebview && tab.label === 'Hydra · Usage limits'));
      await vscode.commands.executeCommand('hydra.openQuotaStatus');
      assert.equal(vscode.window.tabGroups.all.flatMap(group => group.tabs).filter(tab => tab.input instanceof vscode.TabInputWebview && tab.label === 'Hydra · Usage limits').length, 1);
      assert.deepEqual(await vscode.commands.executeCommand('hydra.getQuotaState'), quotasBefore, 'Opening and reopening quota view are passive');
      await vscode.commands.executeCommand('hydra.refreshQuota');
      const quotas = await vscode.commands.executeCommand<QuotaState>('hydra.getQuotaState'); assert.ok(quotas);
      assert.equal(quotas.status, 'checked'); assert.equal(quotas.snapshot?.buckets[0]?.primary?.remainingPercent, 75);
      assert.equal(quotas.snapshot?.buckets[0]?.secondary, undefined); assert.equal(quotas.snapshot?.ordinaryUsageAllowed, undefined);
      assert.ok(!JSON.stringify(quotas).includes('private-fixture-account')); assert.ok(!JSON.stringify(quotas).includes('private-reset-token'));
      assert.deepEqual(await vscode.commands.executeCommand('hydra.listTasks'), tasksBeforeQuota); assert.deepEqual(await vscode.commands.executeCommand('hydra.getSession', discardTask.id), historyBeforeQuota);
      assert.equal(await readFile(path.join(discardTask.worktree, 'codex-requests.jsonl'), 'utf8'), requestsBeforeHold, 'Quota refresh starts no model turn');
      await vscode.workspace.getConfiguration('hydra').update('codexPath', 'relative-invalid-quota', vscode.ConfigurationTarget.Workspace);
      await waitFor(async () => (await vscode.commands.executeCommand<QuotaState>('hydra.getQuotaState'))?.status === 'unchecked');
      assert.equal((await vscode.commands.executeCommand<QuotaState>('hydra.getQuotaState'))?.snapshot, undefined);
      await vscode.commands.executeCommand('hydra.refreshQuota'); assert.equal((await vscode.commands.executeCommand<QuotaState>('hydra.getQuotaState'))?.status, 'error');
      await vscode.workspace.getConfiguration('hydra').update('codexPath', process.env.HYDRA_TEST_CODEX_PROVIDER, vscode.ConfigurationTarget.Workspace);
      await waitFor(async () => (await vscode.commands.executeCommand<QuotaState>('hydra.getQuotaState'))?.status === 'unchecked');
      console.log('PASS: native quota view is passive/reused, explicitly refreshes reported windows, strips identities/reset tokens, preserves exact held tasks/history, makes zero model requests and clears observations on provider configuration changes.');
    } else {
      await assert.rejects(async () => vscode.commands.executeCommand('hydra.openQuotaStatus'), /local Hydra desktop IDE/);
      await assert.rejects(async () => vscode.commands.executeCommand('hydra.refreshQuota'), /trusted local Hydra window/);
      assert.equal((await vscode.commands.executeCommand<QuotaState>('hydra.getQuotaState'))?.status, 'unchecked');
      assert.equal(await readFile(path.join(discardTask.worktree, 'codex-requests.jsonl'), 'utf8'), requestsBeforeHold, 'Rejected quota commands start no model turn');
      console.log('PASS: bundled extension host refuses desktop-only quota commands without refreshing state or starting a provider turn.');
    }
    const resourceTask = await vscode.commands.executeCommand<Task>('hydra.createTask', { title: 'Resource fixture', prompt: 'Resource-aware local fixture', repository, provider: 'codex' }); assert.ok(resourceTask);
    const setupExecutable = process.env.HYDRA_TEST_NODE; assert.ok(setupExecutable);
    const setup = { database: `db_${resourceTask.id}`, service: `service_${resourceTask.id}`, commands: [{ executable: setupExecutable, args: ['-e', 'require("fs").writeFileSync("setup-environment.json",JSON.stringify({cwd:process.cwd(),db:process.env.HYDRA_TASK_DATABASE}));console.log("native setup passed")'] }], timeoutMs: 10000 };
    await vscode.commands.executeCommand('hydra.saveResources', resourceTask.id, setup);
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.startManaged', resourceTask.id), /Run.*setup/);
    await assert.rejects(readFile(path.join(resourceTask.worktree, 'codex-requests.jsonl')), { code: 'ENOENT' });
    await vscode.commands.executeCommand('hydra.runSetup', resourceTask.id);
    await waitFor(async () => (await vscode.commands.executeCommand<Record<string, ResourceView>>('hydra.getResources'))?.[resourceTask.id]?.status === 'passed');
    const setupEvidence = JSON.parse(await readFile(path.join(resourceTask.worktree, 'setup-environment.json'), 'utf8')); assert.equal(setupEvidence.db, setup.database); assert.equal(path.relative(await realpath(setupEvidence.cwd), await realpath(resourceTask.worktree)), '');
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.handoffCodex', resourceTask.id), /resources.*supported/);
    await vscode.commands.executeCommand('hydra.startManaged', resourceTask.id);
    await waitFor(async () => { const view = await vscode.commands.executeCommand<SessionView>('hydra.getSession', resourceTask.id); return view?.turns[0]?.status === 'completed' && !view.active; });
    const environment = JSON.parse(await readFile(path.join(resourceTask.worktree, 'codex-resource-environment.json'), 'utf8')); assert.equal(environment.database, setup.database); assert.equal(environment.service, setup.service);
    await assert.rejects(async () => await vscode.commands.executeCommand('hydra.saveResources', resourceTask.id, setup), /locked/);
    console.log('PASS: native saved setup blocks provider requests until passing, uses the exact checkout and resource environment, passes assignments to managed Codex and locks configuration after launch.');
    await waitFor(async () => (await vscode.commands.executeCommand<CapacityView>('hydra.getCapacity'))?.reserved === 0);
    const capacityRecoveryTask = await vscode.commands.executeCommand<Task>('hydra.createTask', { title: 'Capacity recovery', prompt: 'Fixture terminal only; no provider model request', repository, provider: 'claude' }); assert.ok(capacityRecoveryTask);
    await vscode.commands.executeCommand('hydra.launchTask', capacityRecoveryTask.id); await waitFor(() => correctCwd(capacityRecoveryTask));
    assert.equal((await vscode.commands.executeCommand<CapacityView>('hydra.getCapacity'))?.reserved, 1);
    console.log('PASS: native managed/setup completions release verified profile slots; one owned terminal reservation is deliberately retained for restart acceptance.');
  }
}
