/**
 * Immutable, host-recorded facts for a delegated run. This module does not
 * inspect tasks, create events, persist history, or infer traffic from state.
 */
export const maxDelegationGraphEvents = 512;
const maxIncomingEvents = maxDelegationGraphEvents * 2;

export type DelegationGraphEventKind = 'assignment' | 'dispatch' | 'result-delivery' | 'validation' | 'approval-pause' | 'interruption' | 'acceptance';
export type DelegationGraphParticipant =
  | { kind: 'task'; taskId: string }
  | { kind: 'host' }
  | { kind: 'scheduler' }
  | { kind: 'verification' }
  | { kind: 'integration' };
export type DelegationGraphProducer = 'host' | 'scheduler' | 'verification' | 'integration';
export interface DelegationGraphEvent {
  version: 1;
  /** Durable event identity, generated by the future journal producer. */
  id: string;
  /** Monotonic per parent/run replay order, assigned by the future journal. */
  sequence: number;
  occurredAt: string;
  kind: DelegationGraphEventKind;
  parentId: string;
  runId: string;
  from: DelegationGraphParticipant;
  to: DelegationGraphParticipant;
  /** The component and durable source record that actually observed this fact. */
  provenance: { producer: DelegationGraphProducer; recordId: string };
}

const eventId = (value: unknown): value is string => typeof value === 'string' && /^[a-f0-9]{24}$/.test(value);
const taskId = (value: unknown): value is string => typeof value === 'string' && /^[a-f0-9]{12}$/.test(value);
const timestamp = (value: unknown): value is string => typeof value === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) && Number.isFinite(Date.parse(value)) && new Date(Date.parse(value)).toISOString() === value;
const exact = (value: unknown, keys: readonly string[], error = 'Invalid delegation graph event.') => {
  if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).some(key => !keys.includes(key))) throw new Error(error);
  return value as Record<string, unknown>;
};
function participant(value: unknown): DelegationGraphParticipant {
  const item = exact(value, ['kind', 'taskId']);
  if (item.kind === 'task' && taskId(item.taskId)) return { kind: 'task', taskId: item.taskId };
  if (['host', 'scheduler', 'verification', 'integration'].includes(item.kind as string) && item.taskId === undefined) return { kind: item.kind as Exclude<DelegationGraphParticipant['kind'], 'task'> };
  throw new Error('Invalid delegation graph participant.');
}

const rules: Record<DelegationGraphEventKind, { from: DelegationGraphParticipant['kind']; to: DelegationGraphParticipant['kind']; producer: DelegationGraphProducer }> = {
  assignment: { from: 'task', to: 'task', producer: 'host' },
  dispatch: { from: 'scheduler', to: 'task', producer: 'scheduler' },
  'result-delivery': { from: 'task', to: 'task', producer: 'host' },
  validation: { from: 'verification', to: 'task', producer: 'verification' },
  'approval-pause': { from: 'host', to: 'task', producer: 'host' },
  interruption: { from: 'scheduler', to: 'task', producer: 'scheduler' },
  acceptance: { from: 'integration', to: 'task', producer: 'integration' }
};

/** Parses the first persisted schema. No unversioned/older event existed to migrate. */
export function parseDelegationGraphEvent(value: unknown): DelegationGraphEvent {
  const item = exact(value, ['version', 'id', 'sequence', 'occurredAt', 'kind', 'parentId', 'runId', 'from', 'to', 'provenance']);
  if (item.version !== 1 || !eventId(item.id) || !Number.isSafeInteger(item.sequence) || (item.sequence as number) < 1 || !timestamp(item.occurredAt) || !taskId(item.parentId) || !taskId(item.runId) || !Object.prototype.hasOwnProperty.call(rules, item.kind as string)) throw new Error('Unsupported or invalid delegation graph event schema.');
  const from = participant(item.from), to = participant(item.to), provenance = exact(item.provenance, ['producer', 'recordId']);
  const kind = item.kind as DelegationGraphEventKind, rule = rules[kind];
  if (from.kind !== rule.from || to.kind !== rule.to || provenance.producer !== rule.producer || !eventId(provenance.recordId)) throw new Error('Delegation graph event provenance does not match its recorded lifecycle fact.');
  if (kind === 'assignment' && (from.kind !== 'task' || from.taskId !== item.parentId || to.kind !== 'task' || to.taskId === item.parentId)) throw new Error('Delegation graph assignment does not bind to a distinct recorded child.');
  if (kind === 'result-delivery' && (to.kind !== 'task' || to.taskId !== item.parentId || from.kind !== 'task' || from.taskId === item.parentId)) throw new Error('Delegation graph result delivery does not bind to a distinct recorded child.');
  return { version: 1, id: item.id, sequence: item.sequence as number, occurredAt: item.occurredAt, kind, parentId: item.parentId, runId: item.runId, from, to, provenance: { producer: provenance.producer as DelegationGraphProducer, recordId: provenance.recordId as string } };
}

function sameEvent(left: DelegationGraphEvent, right: DelegationGraphEvent): boolean { return JSON.stringify(left) === JSON.stringify(right); }
function ordered(values: unknown[], maximum: number): DelegationGraphEvent[] {
  if (!Array.isArray(values) || values.length > maximum) throw new Error('Delegation graph event history exceeds its bounded input limit.');
  const byId = new Map<string, DelegationGraphEvent>();
  let binding: string | undefined;
  for (const value of values) {
    const event = parseDelegationGraphEvent(value), prior = byId.get(event.id);
    const currentBinding = `${event.parentId}:${event.runId}`;
    if (binding !== undefined && binding !== currentBinding) throw new Error('Delegation graph event history must contain one parent run.');
    binding = currentBinding;
    if (prior && !sameEvent(prior, event)) throw new Error('Conflicting duplicate delegation graph event ID.');
    byId.set(event.id, event);
  }
  const result = [...byId.values()].sort((left, right) => left.sequence - right.sequence || left.id.localeCompare(right.id));
  if (new Set(result.map(event => event.sequence)).size !== result.length) throw new Error('Delegation graph replay order is ambiguous.');
  return result;
}

/** Validates stored history, suppresses exact duplicate replay records, and returns canonical replay order. */
export function parseDelegationGraphEvents(value: unknown): DelegationGraphEvent[] { return ordered(value as unknown[], maxDelegationGraphEvents); }

/**
 * Explicit retention policy for the future journal: canonicalize first, then
 * evict the oldest replay records. The caller persists both the retained list
 * and, if needed, the returned evicted IDs; this function performs no I/O.
 */
export function boundDelegationGraphEventHistory(value: unknown, limit = maxDelegationGraphEvents): { events: DelegationGraphEvent[]; evicted: string[] } {
  if (!Number.isSafeInteger(limit) || limit < 1 || limit > maxDelegationGraphEvents) throw new Error('Invalid delegation graph event history limit.');
  const all = ordered(value as unknown[], maxIncomingEvents), evicted = all.slice(0, Math.max(0, all.length - limit));
  return { events: all.slice(-limit), evicted: evicted.map(event => event.id) };
}
